# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'AC3.2-Final' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AC3.2-Final
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'SnapKit'
end
